// Downloads the ANAC MADHEL aerodrome/heliport catalog and writes an offline
// snapshot for [BundledZonesApiClient].
//
// Usage (from the app root):
//   dart run packages/zones_api_client/tool/import_madhel.dart
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:zones_api_client/src/madhel_zone_mapper.dart';

Future<void> main() async {
  const url = 'https://datos.anac.gob.ar/madhel/api/v2/airports/';
  final response =
      await http.get(Uri.parse(url)).timeout(const Duration(seconds: 30));
  if (response.statusCode != 200) {
    stderr.writeln('MADHEL fetch failed: HTTP ${response.statusCode}');
    exitCode = 1;
    return;
  }

  final decoded = jsonDecode(response.body);
  if (decoded is! Map<String, dynamic>) {
    stderr.writeln('Unexpected MADHEL response shape');
    exitCode = 1;
    return;
  }

  final results = decoded['results'];
  if (results is! List || results.isEmpty) {
    stderr.writeln('MADHEL results empty');
    exitCode = 1;
    return;
  }

  final zones = MadhelZoneMapper.fromSnapshotJson(results);
  stderr.writeln('MADHEL entries: ${results.length}, zones: ${zones.length}');

  final outputPath =
      Platform.script.resolve('../lib/src/madhel_aerodromes.g.dart');
  final file = File.fromUri(outputPath);
  final jsonLiteral = jsonEncode(results);
  final generatedAt = DateTime.now().toUtc().toIso8601String();
  final entryCount = results.length;

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('//')
    ..writeln(
      '// Generated by: dart run packages/zones_api_client/tool/import_madhel.dart',
    )
    ..writeln('// Source: https://datos.anac.gob.ar/madhel/api/v2/airports/')
    ..writeln('// Generated at: $generatedAt')
    ..writeln('// Entries: $entryCount')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln("import 'package:zones_api_client/src/madhel_zone_mapper.dart';")
    ..writeln("import 'package:zones_api_client/src/models/zone_data.dart';")
    ..writeln()
    ..writeln(
      '/// Offline MADHEL aerodrome/heliport snapshot ($entryCount entries).',
    )
    ..writeln("const _madhelSnapshotJson = r'''")
    ..write(jsonLiteral)
    ..writeln("''';")
    ..writeln()
    ..writeln('/// Parses the bundled MADHEL snapshot into [ZoneData] circles.')
    ..writeln('List<ZoneData> loadBundledMadhelAerodromes() {')
    ..writeln('  final decoded = jsonDecode(_madhelSnapshotJson);')
    ..writeln('  if (decoded is! List) return const [];')
    ..writeln('  return MadhelZoneMapper.fromSnapshotJson(decoded);')
    ..writeln('}');

  await file.writeAsString(buffer.toString());

  stderr.writeln('Wrote ${file.path}');
}
