name: auth_repository
description: Repository for auth session persistence and refresh.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  auth_api_client:
    path: ../auth_api_client
  storage:
    path: ../storage

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.0
  very_good_analysis: ^6.0.0
