name: storage
description: Data client wrapping SharedPreferences for simple key/value storage.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
