name: location_client
description: Data client that wraps the geolocator plugin for device location.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
